"""
ZIP service for packaging Terraform files for download.
Uses in-memory ZIP to avoid filesystem paths and prevent path traversal.
"""
import io
import zipfile
from typing import List
from app.schemas.terraform import TerraformFile


def create_terraform_zip(files: List[TerraformFile], project_name: str) -> io.BytesIO:
    """
    Creates an in-memory ZIP file containing all Terraform files.
    Returns a BytesIO buffer positioned at the start.
    """
    # Sanitize folder name to prevent path traversal
    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
    folder = f"cloudforge-{safe_name}"

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for tf_file in files:
            # Prevent path traversal by using only the basename
            safe_filename = tf_file.filename.replace("..", "").lstrip("/").lstrip("\\")
            arc_path = f"{folder}/{safe_filename}"
            zf.writestr(arc_path, tf_file.content)

        # Add a README inside the zip
        readme_content = f"""# CloudForge Generated Terraform

Project: {project_name}

## Usage

1. Install Terraform: https://developer.hashicorp.com/terraform/install
2. Configure AWS credentials: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
3. Initialize Terraform:
   ```
   terraform init
   ```
4. Review the plan:
   ```
   terraform plan
   ```
5. Apply (when ready):
   ```
   terraform apply
   ```

## Generated Files

""" + "\n".join(f"- `{f.filename}`" for f in files) + """

## Important

This Terraform was generated by CloudForge from your visual architecture.
Always review before applying to production infrastructure.

If `terraform.auto.tfvars` is present it contains generated database passwords —
treat it as a secret and do not commit it to source control.
"""
        zf.writestr(f"{folder}/README.md", readme_content)

    buffer.seek(0)
    return buffer
