"""Idempotent demo seed so a fresh database is immediately usable.

Creates the demo account (demo@cloudforge.io / demo1234) and a ready-to-explore
architecture if they are missing. Enabled by default outside production, or
explicitly via CLOUDFORGE_SEED_DEMO=true; set it to "false" for a clean DB.
"""
import logging
import os

from sqlalchemy import select

from app.database import AsyncSessionLocal
from app.models.architecture import Architecture
from app.models.project import Project
from app.models.user import User
from app.core.security import get_password_hash

logger = logging.getLogger("cloudforge.seed")

DEMO_EMAIL = "demo@cloudforge.io"
DEMO_USERNAME = "demo"
DEMO_PASSWORD = "demo1234"
DEMO_PROJECT_NAME = "3-Tier Demo App"


def should_seed() -> bool:
    value = os.getenv("CLOUDFORGE_SEED_DEMO")
    if value is not None:
        return value.strip().lower() in ("1", "true", "yes", "on")
    env = os.getenv("CLOUDFORGE_ENV", os.getenv("ENV", "development")).lower()
    return env != "production"


def _node(nid, rtype, label, props, x, y):
    return {
        "id": nid,
        "type": "resourceNode",
        "position": {"x": x, "y": y},
        "data": {"label": label, "resourceType": rtype, "provider": "aws", "properties": props},
    }


def _demo_graph():
    nodes = [
        _node("vpc", "vpc", "demo-vpc", {"name": "demo-vpc", "cidr": "10.0.0.0/16", "environment": "development"}, 480, 40),
        _node("subnet-a", "subnet", "public-subnet-a", {"name": "public-subnet-a", "cidr": "10.0.1.0/24", "mapPublicIp": True}, 240, 220),
        _node("subnet-b", "subnet", "public-subnet-b", {"name": "public-subnet-b", "cidr": "10.0.2.0/24", "mapPublicIp": True}, 720, 220),
        _node("igw", "internet_gateway", "demo-igw", {"name": "demo-igw"}, 40, 120),
        _node("rt", "route_table", "public-routes", {"name": "public-routes", "destinationCidr": "0.0.0.0/0"}, 920, 120),
        _node("lb", "load_balancer", "demo-lb", {"name": "demo-lb", "lbType": "application", "internal": False}, 480, 400),
        _node("ec2-1", "ec2", "web-server-1", {"name": "web-server-1", "instanceType": "t3.micro", "associatePublicIp": True}, 240, 560),
        _node("ec2-2", "ec2", "web-server-2", {"name": "web-server-2", "instanceType": "t3.micro", "associatePublicIp": True}, 720, 560),
        _node("sg", "security_group", "web-sg", {"name": "web-sg", "description": "HTTP/HTTPS to the web tier"}, 960, 460),
        _node("s3", "s3", "demo-assets", {"bucketName": "cloudforge-demo-assets", "versioning": False}, 480, 720),
    ]
    pairs = [
        ("vpc", "subnet-a"), ("vpc", "subnet-b"), ("vpc", "igw"), ("vpc", "rt"),
        ("subnet-a", "rt"),
        ("lb", "subnet-a"), ("lb", "subnet-b"),
        ("ec2-1", "subnet-a"), ("ec2-2", "subnet-b"),
        ("lb", "ec2-1"), ("lb", "ec2-2"),
        ("sg", "ec2-1"), ("sg", "ec2-2"), ("sg", "lb"),
    ]
    edges = [{"id": f"e-{s}-{t}", "source": s, "target": t} for s, t in pairs]
    return nodes, edges


async def ensure_demo_seed() -> None:
    async with AsyncSessionLocal() as db:
        result = await db.execute(select(User).where(User.email == DEMO_EMAIL))
        user = result.scalar_one_or_none()
        if user is None:
            user = User(
                email=DEMO_EMAIL,
                username=DEMO_USERNAME,
                hashed_password=get_password_hash(DEMO_PASSWORD),
            )
            db.add(user)
            await db.flush()
            logger.info("seed: created demo user %s", DEMO_EMAIL)

        result = await db.execute(
            select(Project).where(
                Project.user_id == user.id, Project.name == DEMO_PROJECT_NAME
            )
        )
        if result.scalar_one_or_none() is not None:
            await db.commit()
            return

        project = Project(
            user_id=user.id,
            name=DEMO_PROJECT_NAME,
            description="VPC + ALB + EC2 + S3 demo architecture generated by the seed.",
            provider="aws",
            status="saved",
        )
        db.add(project)
        await db.flush()

        nodes, edges = _demo_graph()
        db.add(Architecture(project_id=project.id, nodes=nodes, edges=edges, aws_region="us-east-1"))
        await db.commit()
        logger.info("seed: created demo project '%s' (%s)", DEMO_PROJECT_NAME, project.id)
